name: Version check

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main

jobs:
  version-check:
    name: Check tags
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check version format and availability
        run: chmod +x .github/deploy/version_check.sh && .github/deploy/version_check.sh
